services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "cd spimex_trading_app && alembic upgrade head && python parser.py && uvicorn main:main_app --host 0.0.0.0 --port 8000 --reload "
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - ./.env

  celery:
    build: .
    tty: true
    command: sh -c "cd spimex_trading_app && celery -A celery_app worker --loglevel=info -P eventlet"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app

  celery-beat:
    build: .
    tty: true
    command: sh -c "cd spimex_trading_app && celery -A celery_app beat --loglevel=info"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app

volumes:
  pg_data: